name = "timer-board"
main = "worker.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "timer-board-db"
database_id = "db815890-1997-4df4-921e-30ce83cb6c78"
