name = "timerboard"
main = "worker.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "timer-board-db"
database_id = "db815890-1997-4df4-921e-30ce83cb6c78"

[[rules]]
type = "ESModule"
globs = ["worker.js"]

[secrets]
required = [
"INITIAL_ADMIN_PASSWORD",
"INITIAL_USER_PASSWORD",
"INITIAL_VIEWER_PASSWORD"
]
